version: '3'
services:
  vault:
    image: "vault:1.0.2"
    hostname: "vault"
    entrypoint: vault server -dev -config=/etc/vault/config.hcl
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/etc/vault:ro
      - plugin-dir:/var/vault/plugins

  vault-init:
    build:
      dockerfile: dev/plugin/Dockerfile
      context: ../
      args:
        VAULT_VERSION: 1.0.2
    entrypoint: entrypoint.bash
    depends_on:
      - vault
    links:
      - "vault:vault"
    environment:
      VAULT_PLUGIN_DIR: "/var/vault/plugins"
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root"
    volumes:
      - ./plugin/entrypoint:/usr/local/bin:ro
      - plugin-dir:/var/vault/plugins

volumes:
  plugin-dir:
