version: '3'
services:
  vault:
    image: "vault:1.0.2"
    hostname: "vault"
    entrypoint: vault server -dev -config=/etc/vault/config.hcl
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
    ports:
      - "8200:8200"
    volumes:
      - shared:/var/vault/plugins
      - ./compose/vault/etc/vault:/etc/vault:ro

  plugin:
    build:
      dockerfile: ./dev/compose/plugin/Dockerfile
      context: ../
      args:
        VAULT_VERSION: 1.0.2
    entrypoint: /usr/local/bin/entrypoint.bash
    depends_on:
      - vault
    links:
      - "vault:vault"
    environment:
      VAULT_TOKEN: "root"
      VAULT_ADDR: "http://vault:8200"
      VAULT_PLUGIN_DIR: "/var/vault/plugins"
    volumes:
      - shared:/var/vault/plugins
      - ./compose/plugin/usr/local/bin:/usr/local/bin:ro

# Use a volume to share files between containers
volumes:
  shared:
